package com.globant.training.inventorysample;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;

/**
 * Base applicaiton generated by Spring initializr.
 *
 * Here is recommended to add annotations
 * - ComponentScan with list of packages where injectable spring components reside.
 * - EntityScan with list of packages with JPA entities.
 */
@ComponentScan(basePackages = {"com.globant.training.inventorysample"})
@EntityScan(basePackages = {"com.globant.training.inventorysample"})
@SpringBootApplication
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
